apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
     name: voting-app-pod
     app: demo-voting-app
spec:
  replicas: 2
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
      name: voting-app-service
      app: demo-voting-app
spec:
  selector:
    app: demo-voting-app
    name: voting-app-pod
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer