apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
     name: worker-app-pod
     app: demo-voting-app
spec:
  replicas: 1
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker

